#!/usr/bin/env python3
"""night-014: Sampling-regime dual-predicate measurement (MEASUREMENT ONLY).

DS-032 Part 2 established that suppression-only under sampling
(do_sample=True, temp=0.8, top_p=0.85) rescues 50/50 heldout_degenerate_v2
records with EOS 0.20 and prose Distinct-2 0.97 — the strongest result in the
entire measurement series. But the dual-predicate detector (RFC-004 Amendment
A3, Option C) has never been tested under do_sample=True. Every gate script
uses greedy decoding, while the production use case for a variety governor is
overwhelmingly sampling-based generation.

This probe measures the dual-predicate + production logit-penalty actuation
under sampling on all three degenerate fixtures. Two arms:

  Arm 1 — production actuation (unconditional suppression + CTR-triggered
          kickstart). This is the Option C configuration currently in the
          controller. Measures whether the dual-predicate detection fires
          correctly under sampling and whether production actuation rescues
          at rates comparable to greedy.

  Arm 2 — spectral-gated kickstart. Tests whether the DS-035 t2s macro-loop
          rescue transfers to the sampling regime where kickstart can fire
          without triggering EOS death (the DS-029 interaction pathology was
          a greedy-only phenomenon).

MEASUREMENT ONLY. No controller edits, no thresholds, no new actuation design.

Frozen dual-predicate rule (DS-034e config, band_low hardening):

    bigram_collapse   = (token_diversity < 0.30) AND (trailing_ctr < 0.30)
    if bigram_collapse: bigram_ctr += 1 else: bigram_ctr = 0
    bigram_fire       = bigram_ctr >= 2

    spectral_collapse = (layer_2_pr is not None) AND (layer_2_pr < 8.216097)
    if spectral_collapse: spectral_ctr += 1 else: spectral_ctr = 0
    if bigram_ctr < 2:
        spectral_fire = (spectral_ctr >= 2) AND (token_diversity < 0.40)
    else:
        spectral_fire = spectral_ctr >= 2

    if is_code_syntax_context(trailing_text):
        spectral_fire = False

    is_collapsed = bigram_fire OR spectral_fire

Sampling parameters: do_sample=True, temperature=0.8, top_p=0.85 (matching
DS-032 Part 2 configuration). SEED=42. KV-cache incremental generation.

Arm 1 (production actuation, Option C):
  - Unconditional token suppression at EVERY step where active_loop_ids is
    non-empty (cooldown=8, penalty=-5.0).
  - Kickstart triggers on trailing_ctr < 0.50 AND active_loop_ids (production
    behavior, not spectral-gated). Matches the controller after Option C.

Arm 2 (spectral-gated kickstart):
  - Same unconditional token suppression as Arm 1.
  - Kickstart triggers on spectral_fire AND trailing_ctr < 0.50 AND
    active_loop_ids (matching the DS-035 configuration that produced 11 t2s
    rescues). The narrow night-007 trigger (spectral_fire alone) is NOT used.

Fixtures:
  A: tests/fixtures/t2s_degenerate.jsonl (night-001; N=100). record["text"]
     as prompt.
  B: tests/fixtures/qwen_degenerate.jsonl (ds-004; N=100). record["prompt"]
     as prompt.
  C: tests/fixtures/heldout_degenerate_v2.jsonl (ds-027; N=100). 50-record
     seeded subset random.Random(42).sample sorted by record id.
     record["mutated_prompt"] as prompt.

Reused data (do NOT re-run):
  - Greedy rescue-rate baselines: DS-035 (dual_predicate_rescue_results.jsonl)
    for Fixtures A/B; DS-035 heldout_v2 rate (reusing DS-028 layer-2 dormant)
    for Fixture C. Used ONLY for the greedy comparison column in Table 1.
  - Greedy fire-type counts: night-008 (hybrid_ctr_gating_results.jsonl) for
    the Table 3 greedy comparison column.
  - DS-032 Part 2 (cooldown_validation_results.jsonl, part==2) suppression-only
    sampling baseline for the Table 2 comparison on Fixture C.

LIVE data generated by this probe:
  - Sampling dormant baselines for ALL records (do_sample=True, temp=0.8,
    top_p=0.85, no hooks, no suppression, no kickstart) — generated fresh
    because no pre-existing sampling dormant baselines exist.
  - Arm 1 active for ALL records.
  - Arm 2 active for ALL records.

Environment notes (identical to ds-025/ds-033/ds-034c/ds-035/night-004):
  - torch 2.13 CUDA bmm_outer_product Triton override is deregistered
    (env-only; no C compiler in the container).
  - Import convention: sys.path.insert(0, parents[2]) resolves to "/" in the
    container; `import AVG.*` resolves via the /AVG mount.
  - HF cache is read-only here; fall back to HF_HOME=/tmp/hf_cache only if the
    pinned revision is not cached.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import time
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Set, Tuple

os.environ.setdefault("TORCH_DISABLE_NATIVE_JIT", "1")

import numpy as np
import torch
import torch.nn as nn

# Standard root-as-package header. From scripts/, parents[2] resolves to '/';
# `import AVG.*` resolves via the /AVG mount. (Protocol import convention.)
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
print(f"[import] path added: {Path(__file__).resolve().parents[2]}")

# Env-only adaptation: deregister torch 2.13's CUDA bmm Triton override.
try:
    from torch._native import triton_utils as _triton_utils

    _triton_utils.deregister_op_overrides()
    print("[env] torch bmm Triton override deregistered")
except Exception as _env_e:  # pragma: no cover - env dependent
    print(f"[env] bmm override deregistration skipped: {_env_e}")

from transformers import AutoModelForCausalLM, AutoTokenizer  # noqa: E402
from AVG.core.metrics import (  # noqa: E402
    compute_coherent_token_ratio,
    is_code_syntax_context,
    participation_ratio,
)
from AVG.governor.controller import (  # noqa: E402
    compute_token_distinct_2_fast,
    sample_top_p,
)

# ---------------------------------------------------------------------------
# Fixed seed provenance
# ---------------------------------------------------------------------------
SEED = 42  # night-014 measurement seed (matches ds-025..ds-035, DS-032 Part 2)
MODEL_NAME = "Qwen/Qwen2.5-1.5B"
MODEL_REVISION = "8faed761d45a263340a0528343f099c05c9a4323"
MAX_NEW_TOKENS = 128  # decoding steps (EOS break; EOS token included)
ANALYSIS_WINDOW = 24  # rolling 24-token PR / distinct-2 window (Gate 2.3 conv)
HOOK_LAYER = 2  # RFC-004 layer-2 forward hook
NUM_RECORDS_C = 50  # Fixture C: seeded 50-record subset (random.Random(42))

# Frozen thresholds (ds-025 Part A freeze; must match FROZEN_THRESHOLDS.md).
# DS-034e configuration: spectral_collapse uses band_low (hardened), NOT T_PR.
T_PR_2_TASK = 10.954796  # PR < T -> spectral fire (primary, DS-034c)
BAND_LOW_TASK = 8.216097  # spectral_collapse threshold (band_low, frozen)

# Sampling regime (DS-032 Part 2 configuration).
SAMPLING_TEMPERATURE = 0.8
SAMPLING_TOP_P = 0.85

# Production controller settings (controller.py defaults, DS-033/DS-034c task).
COOLDOWN = 8          # controller.py:137 (cooldown_steps=8)
PENALTY = -5.0        # controller.py:745 (next_logits[:, tid] -= 5.0)
TOP_P = 0.85          # controller.py:138 (top_p=0.85)
CTR_THRESHOLD = 0.50  # controller.py:691 (trailing_ctr < 0.50)
DIVERSITY_CTR_GATE = 0.40  # controller.py:683 (token_diversity < 0.40)
EVERY_K = 2           # controller.py:136 (every_k=2)
TRAILING_GEN_WINDOW = 16  # controller.py:686 (trailing 16 generated tokens)
KICKSTART_COUNTER_INIT = 3  # controller.py:692
KICKSTART_PENALTIES: Dict[int, float] = {3: -1e4, 2: -5.0, 1: -2.0}  # controller.py:753-758

# Collapse predicate (controller.py:464, use_code_filter=False):
#   is_token_loop = token_diversity < 0.30 and trailing_ctr < 0.30
COLLAPSE_DIVERSITY = 0.30
COLLAPSE_CTR = 0.30

# DS-034e spectral corroboration on spectral-only fires (bigram_ctr < 2).
SPECTRAL_CORROBORATION_DIVERSITY = 0.40

# Paths
T2S_DEG = Path("tests/fixtures/t2s_degenerate.jsonl")
QWEN_DEG = Path("tests/fixtures/qwen_degenerate.jsonl")
HELDOUT_DEG_V2 = Path("tests/fixtures/heldout_degenerate_v2.jsonl")
FROZEN_THRESHOLDS_PATH = Path("docs/gate23/FROZEN_THRESHOLDS.md")
DS035_JSONL = Path("docs/gate23/dual_predicate_rescue_results.jsonl")
DS028_JSONL = Path("docs/gate23/layer_effect_persistent_results.jsonl")
DS032_JSONL = Path("docs/gate23/cooldown_validation_results.jsonl")
NIGHT008_JSONL = Path("docs/gate23/hybrid_ctr_gating_results.jsonl")
OUTPUT_JSONL = Path("docs/gate23/sampling_dual_predicate_results.jsonl")
OUTPUT_MD = Path("docs/gate23/SAMPLING_DUAL_PREDICATE_RESULTS.md")

# HF cache: model is already present in the read-only system cache. Do NOT force
# an HF_HOME fallback to /tmp (that would re-download 1.5B weights). Only fall
# back if the pinned model is not present.
_DEFAULT_HF_CACHE = str(Path.home() / ".cache" / "huggingface")
if not os.access(_DEFAULT_HF_CACHE, os.W_OK):
    _pinned_dir = os.path.join(
        _DEFAULT_HF_CACHE, "hub", "models--Qwen--Qwen2.5-1.5B",
        "snapshots", MODEL_REVISION,
    )
    if not os.path.isdir(_pinned_dir):
        _fallback = "/tmp/hf_cache"
        os.makedirs(_fallback, exist_ok=True)
        os.environ.setdefault("HF_HOME", _fallback)
        print(f"[env] HF_HOME fallback -> {_fallback} (pinned revision not cached)")
    else:
        print("[env] read-only HF cache used directly (pinned revision present)")


# ---------------------------------------------------------------------------
# Seeding
# ---------------------------------------------------------------------------
def seed_all(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------
def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


# ---------------------------------------------------------------------------
# Frozen threshold (read from the Part A freeze file; do NOT re-derive)
# ---------------------------------------------------------------------------
def load_frozen_thresholds(path: Path) -> Tuple[float, float]:
    """Parse the machine-parseable JSON freeze block from FROZEN_THRESHOLDS.md
    and return (T_PR(2), band_low(2)). STOP if the values disagree with the
    task-specified frozen values."""
    text = path.read_text(encoding="utf-8")
    start = text.find("```json")
    if start == -1:
        raise SystemExit("[STOP] FROZEN_THRESHOLDS.md has no ```json freeze block.")
    start = text.find("\n", start) + 1
    end = text.find("```", start)
    if end == -1:
        raise SystemExit("[STOP] FROZEN_THRESHOLDS.md freeze block is unterminated.")
    freeze = json.loads(text[start:end])
    t_pr = float(freeze["layers"]["2"]["pr"]["T"])
    band_low = float(freeze["layers"]["2"]["pr"]["band_low"])
    if abs(t_pr - T_PR_2_TASK) > 1e-9:
        raise SystemExit(
            f"[STOP] FROZEN_THRESHOLDS.md T_PR(2)={t_pr:.6f} does not match the "
            f"task-specified frozen value {T_PR_2_TASK:.6f}. Do NOT re-derive "
            f"or adjust thresholds."
        )
    if abs(band_low - BAND_LOW_TASK) > 1e-9:
        raise SystemExit(
            f"[STOP] FROZEN_THRESHOLDS.md band_low(2)={band_low:.6f} does not "
            f"match the task-specified frozen value {BAND_LOW_TASK:.6f}. Do NOT "
            f"re-derive or adjust thresholds."
        )
    return t_pr, band_low


# ---------------------------------------------------------------------------
# Vocabulary subsets (production _cache_vocabulary_subsets logic)
# ---------------------------------------------------------------------------
def cache_vocabulary_subsets(
    tokenizer: Any,
) -> Tuple[Set[int], Set[int]]:
    """Production _cache_vocabulary_subsets() logic (controller.py:158-175).

    Iterate the tokenizer vocab; classify each id as prose (single a/I/A or
    len>=2 alpha-only with a vowel) or non-prose.
    Returns (prose_ids, non_prose_ids).
    """
    vocab_size = getattr(
        tokenizer, "vocab_size", getattr(tokenizer, "len", 151646)
    )
    vowels = set("aeiouyAEIOUY")
    prose: Set[int] = set()
    non_prose: Set[int] = set()
    for tid in range(int(vocab_size)):
        try:
            tok_str = tokenizer.decode([tid])
        except Exception:
            continue
        clean_str = tok_str.strip()
        if clean_str in ("a", "I", "A") or (
            len(clean_str) >= 2
            and all(c.isalpha() or c in ("'", "-") for c in clean_str)
            and any(c in vowels for c in clean_str)
        ):
            prose.add(tid)
        else:
            non_prose.add(tid)
    return prose, non_prose


# ---------------------------------------------------------------------------
# Layer-2 PR measurement hook (identical to DS-034b / DS-034c instrument)
# ---------------------------------------------------------------------------
def make_layer2_pr_hook(
    analysis_window: int = ANALYSIS_WINDOW,
) -> Tuple[Callable[..., Any], List[torch.Tensor], List[Dict[str, Any]]]:
    """Create a layer-2 forward-hook measurement instrument.

    At each decoding step (one forward pass per step), capture the hidden state
    at the current token position (the last position of the sequence, matching
    the governor's shadow-hook capture at ``[:, -1:, :]``), append it to a ring
    buffer of the trailing ``analysis_window`` generated hidden states, and when
    the buffer has >= ``analysis_window`` entries compute
    ``participation_ratio()`` over the window (float32, matching ds-005/ds-010
    numerical discipline). The PR value is logged; the hook returns ``output``
    unchanged (pure measurement instrument).
    """
    buffer: List[torch.Tensor] = []
    pr_log: List[Dict[str, Any]] = []
    step_counter = {"n": 0}

    def hook_fn(
        module: nn.Module,
        input_args: Tuple[Any, ...],
        output: Any,
    ) -> Any:
        hs = output[0] if isinstance(output, tuple) else output
        # Current token position = last position of the (seq_len==1) input.
        current = hs[:, -1:, :].detach().to(dtype=torch.float32)  # (1,1,d)
        buffer.append(current)
        if len(buffer) > analysis_window:
            buffer.pop(0)  # ring buffer: keep trailing `analysis_window`
        step = int(step_counter["n"])
        step_counter["n"] += 1
        if len(buffer) >= analysis_window:
            win = torch.cat(buffer[-analysis_window:], dim=1)  # (1,24,d)
            pr = participation_ratio(win).item()
            pr_log.append({"step": step, "pr": float(pr)})
        return output

    return hook_fn, buffer, pr_log


# ---------------------------------------------------------------------------
# KV-cache generation: sampling dormant (plain sampling, no hooks)
# ---------------------------------------------------------------------------
@torch.no_grad()
def sampling_generate_dormant(
    model: torch.nn.Module,
    tokenizer: Any,
    prompt: str,
    max_new_tokens: int = MAX_NEW_TOKENS,
) -> Dict[str, Any]:
    """Sampling (do_sample=True) dormant generation with KV-cache.

    Plain sampling: do_sample=True, temperature=0.8, top_p=0.85 applied at
    every step. No hooks, no suppression, no kickstart, no residual
    interventions. seed_all(SEED) is called at entry so every generation
    starts from the same RNG state (deterministic sampling; DS-032 Part 2
    smoke confirmed this is reproducible).

    Pre-fill the prompt once (use_cache=True), then decode one token at a time
    with past_key_values. EOS break (EOS token is included in generated ids,
    matching the ds-029..ds-033 convention).
    """
    seed_all(SEED)
    enc = tokenizer(prompt, return_tensors="pt").to(model.device)
    prompt_ids = enc["input_ids"]
    prompt_len = int(prompt_ids.shape[-1])
    eos_id = tokenizer.eos_token_id

    # Pre-fill: one forward pass over the full prompt.
    out = model(prompt_ids, use_cache=True)
    past = out.past_key_values
    next_logits = out.logits[:, -1, :].clone().float()

    generated: List[torch.Tensor] = []
    for _step in range(max_new_tokens):
        logits = next_logits.clone()
        logits = sample_top_p(logits, top_p=SAMPLING_TOP_P)
        logits = logits / max(SAMPLING_TEMPERATURE, 1e-5)
        probs = torch.softmax(logits, dim=-1)
        next_token = torch.multinomial(probs, num_samples=1)
        generated.append(next_token)
        if int(next_token.item()) == eos_id:
            break
        # Decoding loop: forward a single token with the KV cache.
        out = model(next_token, past_key_values=past, use_cache=True)
        past = out.past_key_values
        next_logits = out.logits[:, -1, :].clone().float()

    ids = (
        torch.cat(generated, dim=1)
        if generated
        else torch.empty(1, 0, dtype=torch.long, device=model.device)
    )
    return {
        "generated_ids": ids,
        "prompt_len": prompt_len,
        "n_generated": int(ids.shape[-1]),
    }


# ---------------------------------------------------------------------------
# KV-cache generation: sampling active (dual-predicate + logit-penalty)
# ---------------------------------------------------------------------------
@torch.no_grad()
def sampling_generate_active(
    model: torch.nn.Module,
    tokenizer: Any,
    prompt: str,
    non_prose_ids: Set[int],
    spectral_threshold: float,
    kickstart_mode: str,
    max_new_tokens: int = MAX_NEW_TOKENS,
) -> Dict[str, Any]:
    """Sampling (do_sample=True) active generation under night-014.

    KV-cache incremental generation (pre-fill once, then single-token forwards
    with past_key_values). The layer-2 forward hook captures hidden states at
    each decoding step (seq_len==1) into a rolling 24-token ring buffer and
    computes participation_ratio() from step 23 onward.

    Frozen DS-034e dual-predicate rule (exact, unchanged):
        bigram_collapse   = (token_diversity < 0.30) AND (trailing_ctr < 0.30)
        if bigram_collapse: bigram_ctr += 1 else: bigram_ctr = 0
        bigram_fire       = bigram_ctr >= 2

        spectral_collapse = (layer_2_pr is not None) AND (layer_2_pr < spectral_threshold)
        if spectral_collapse: spectral_ctr += 1 else: spectral_ctr = 0
        if bigram_ctr < 2:
            spectral_fire = (spectral_ctr >= 2) AND (token_diversity < 0.40)
        else:
            spectral_fire = spectral_ctr >= 2

        if is_code_syntax_context(trailing_text):
            spectral_fire = False

        is_collapsed = bigram_fire OR spectral_fire

    Arm 1 (kickstart_mode='production') — production actuation (Option C):
      - UNCONDITIONAL token suppression: at EVERY step, if active_loop_ids is
        non-empty, add ALL active_loop_ids to the cooldown dict (=8). Matches
        the production combined path (controller.py:677-679).
      - Kickstart trigger: trailing_ctr < 0.50 AND active_loop_ids non-empty
        (production behavior, not spectral-gated).

    Arm 2 (kickstart_mode='spectral') — spectral-gated kickstart:
      - Same unconditional token suppression as Arm 1.
      - Kickstart trigger: spectral_fire AND trailing_ctr < 0.50 AND
        active_loop_ids non-empty (matching the DS-035 configuration that
        produced 11 t2s rescues). The night-007 narrow trigger
        (spectral_fire alone) is NOT used.

    Both arms: top_p=0.85 when either mechanism is active; temperature=0.8;
    do_sample=True (softmax + multinomial). NO residual hooks. Fire events are
    logged when is_collapsed is true (detection liveness; the dual-predicate
    does not gate actuation).
    """
    seed_all(SEED)
    enc = tokenizer(prompt, return_tensors="pt").to(model.device)
    prompt_ids = enc["input_ids"]
    prompt_len = int(prompt_ids.shape[-1])
    eos_id = tokenizer.eos_token_id

    # Pre-fill: one forward pass over the full prompt.
    out = model(prompt_ids, use_cache=True)
    past = out.past_key_values
    next_logits = out.logits[:, -1, :].clone().float()
    input_ids = prompt_ids

    # Register the layer-2 spectral hook AFTER pre-fill so the rolling buffer
    # only contains hidden states from decoding steps (seq_len==1), matching
    # the DS-034b/DS-034c hook pattern.
    hook_fn, buffer, pr_log = make_layer2_pr_hook(ANALYSIS_WINDOW)
    blocks = model.model.layers
    handle = blocks[HOOK_LAYER].register_forward_hook(hook_fn)

    active_suppress: Dict[int, int] = {}
    kickstart_counter = 0
    bigram_ctr = 0
    spectral_ctr = 0
    fire_events: List[Dict[str, Any]] = []
    n_suppression_steps = 0
    n_kickstart_events = 0
    n_bigram_collapse_steps = 0
    n_spectral_collapse_steps = 0
    n_bigram_fire_steps = 0
    n_spectral_fire_steps = 0
    n_both_fire_steps = 0
    generated: List[torch.Tensor] = []

    try:
        for step in range(max_new_tokens):
            # ---- 1. Bigram predicate: fast integer-only token proxy ----
            token_diversity, active_loop_ids = compute_token_distinct_2_fast(
                input_ids, prompt_len=prompt_len, window_len=ANALYSIS_WINDOW
            )

            # ---- 2. CTR sub-sampling + code-context (every_k=2 or div<0.40) ----
            trailing_ctr = 1.0
            is_code_context = False
            if token_diversity < DIVERSITY_CTR_GATE or step % EVERY_K == 0:
                recent_gen = (
                    input_ids[0, prompt_len:]
                    if input_ids.shape[-1] > prompt_len
                    else input_ids[0]
                )
                recent_tokens = (
                    recent_gen[-TRAILING_GEN_WINDOW:]
                    if recent_gen.numel() > 0
                    else input_ids[0, -TRAILING_GEN_WINDOW:]
                )
                trailing_text = tokenizer.decode(
                    recent_tokens, skip_special_tokens=True
                )
                trailing_ctr = compute_coherent_token_ratio(trailing_text)
                is_code_context = is_code_syntax_context(trailing_text)

            # ---- 3. Spectral predicate: latest PR from the layer-2 hook ----
            pr = pr_log[-1]["pr"] if pr_log else None

            # ---- 4. Frozen DS-034e dual-predicate OR rule (exact) ----
            bigram_collapse = bool(
                token_diversity < COLLAPSE_DIVERSITY
                and trailing_ctr < COLLAPSE_CTR
            )
            if bigram_collapse:
                bigram_ctr += 1
            else:
                bigram_ctr = 0
            bigram_fire = bool(bigram_ctr >= 2)

            spectral_collapse = bool(
                pr is not None and pr < spectral_threshold
            )
            if spectral_collapse:
                spectral_ctr += 1
            else:
                spectral_ctr = 0
            if bigram_ctr < 2:
                spectral_fire = bool(
                    spectral_ctr >= 2
                    and token_diversity < SPECTRAL_CORROBORATION_DIVERSITY
                )
            else:
                spectral_fire = bool(spectral_ctr >= 2)
            if is_code_context:
                spectral_fire = False

            is_collapsed = bool(bigram_fire or spectral_fire)

            n_bigram_collapse_steps += int(bigram_collapse)
            n_spectral_collapse_steps += int(spectral_collapse)
            n_bigram_fire_steps += int(bigram_fire)
            n_spectral_fire_steps += int(spectral_fire)
            n_both_fire_steps += int(bigram_fire and spectral_fire)

            # ---- 5. Actuation: UNCONDITIONAL token suppression ----
            # Production combined path (controller.py:677-679): add ALL
            # active_loop_ids to the cooldown dict at EVERY step where they are
            # detected, regardless of predicate state.
            if active_loop_ids:
                for tid in active_loop_ids:
                    active_suppress[tid] = COOLDOWN

            # ---- 6. Kickstart trigger (arm-dependent) ----
            if kickstart_mode == "production":
                kickstart_fire = bool(
                    trailing_ctr < CTR_THRESHOLD and active_loop_ids
                )
            elif kickstart_mode == "spectral":
                kickstart_fire = bool(
                    spectral_fire
                    and trailing_ctr < CTR_THRESHOLD
                    and active_loop_ids
                )
            else:  # pragma: no cover - validated at call site
                raise ValueError(f"unknown kickstart_mode: {kickstart_mode}")
            if kickstart_fire:
                kickstart_counter = KICKSTART_COUNTER_INIT
                n_kickstart_events += 1

            # ---- 7. Fire-event logging (dual-predicate detection liveness) ----
            if is_collapsed:
                triggers: List[str] = []
                if bigram_fire:
                    triggers.append("bigram")
                if spectral_fire:
                    triggers.append("spectral")
                fire_events.append({
                    "step": int(step),
                    "trigger": "+".join(triggers) if triggers else "none",
                    "bigram_fire": bool(bigram_fire),
                    "spectral_fire": bool(spectral_fire),
                    "bigram_collapse": bool(bigram_collapse),
                    "spectral_collapse": bool(spectral_collapse),
                    "bigram_ctr": int(bigram_ctr),
                    "spectral_ctr": int(spectral_ctr),
                    "pr": pr,
                    "token_diversity": float(token_diversity),
                    "trailing_ctr": float(trailing_ctr),
                    "is_code_context": bool(is_code_context),
                })

            # ---- 8. Production logit-penalty path ----
            logits = next_logits.clone()
            n_suppressed = 0
            if active_suppress:
                for tid, steps_left in list(active_suppress.items()):
                    if steps_left > 0:
                        logits[:, tid] += PENALTY
                        active_suppress[tid] -= 1
                        n_suppressed += 1
                    else:
                        del active_suppress[tid]
            if n_suppressed > 0:
                n_suppression_steps += 1

            kick_penalty_value = 0.0
            if kickstart_counter > 0:
                if non_prose_ids:
                    non_prose_tensor = torch.tensor(
                        list(non_prose_ids), device=logits.device
                    )
                    kick_penalty_value = KICKSTART_PENALTIES.get(
                        kickstart_counter, -2.0
                    )
                    logits[:, non_prose_tensor] += kick_penalty_value
                kickstart_counter -= 1

            if active_suppress or kickstart_counter > 0:
                logits = sample_top_p(logits, top_p=SAMPLING_TOP_P)

            # ---- 9. Temperature + sample (do_sample=True) ----
            logits = logits / max(SAMPLING_TEMPERATURE, 1e-5)
            probs = torch.softmax(logits, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)
            generated.append(next_token)
            if int(next_token.item()) == eos_id:
                break

            # ---- 10. Decoding loop: forward a single token with the KV cache ----
            out = model(next_token, past_key_values=past, use_cache=True)
            past = out.past_key_values
            next_logits = out.logits[:, -1, :].clone().float()

            # ---- 11. Append to input_ids for the next step's bigram ----
            input_ids = torch.cat([input_ids, next_token], dim=-1)
    finally:
        # Spectral hook MUST always be removed, even on exception.
        handle.remove()

    ids = (
        torch.cat(generated, dim=1)
        if generated
        else torch.empty(1, 0, dtype=torch.long, device=model.device)
    )
    pr_vals = [p["pr"] for p in pr_log]
    return {
        "generated_ids": ids,
        "prompt_len": prompt_len,
        "n_generated": int(ids.shape[-1]),
        "pr_log": pr_log,
        "n_pr_values": len(pr_log),
        "pr_mean": float(np.mean(pr_vals)) if pr_vals else None,
        "pr_min": float(np.min(pr_vals)) if pr_vals else None,
        "pr_max": float(np.max(pr_vals)) if pr_vals else None,
        "pr_first": float(pr_vals[0]) if pr_vals else None,
        "pr_last": float(pr_vals[-1]) if pr_vals else None,
        "fire_events": fire_events,
        "fire_count": len(fire_events),
        "n_bigram_fire_steps": n_bigram_fire_steps,
        "n_spectral_fire_steps": n_spectral_fire_steps,
        "n_both_fire_steps": n_both_fire_steps,
        "n_suppression_steps": n_suppression_steps,
        "n_kickstart_events": n_kickstart_events,
        "n_bigram_collapse_steps": n_bigram_collapse_steps,
        "n_spectral_collapse_steps": n_spectral_collapse_steps,
        "kickstart_mode": kickstart_mode,
    }


# ---------------------------------------------------------------------------
# Metric helpers
# ---------------------------------------------------------------------------
def continuation_distinct2(generated_ids: torch.Tensor) -> float:
    """Distinct-2 over the trailing 24 generated tokens (ds-025 convention)."""
    if generated_ids.shape[-1] == 0:
        return 1.0
    d2, _ = compute_token_distinct_2_fast(
        generated_ids, prompt_len=0, window_len=ANALYSIS_WINDOW
    )
    return float(d2)


def continuation_ctr(tokenizer: Any, generated_ids: torch.Tensor) -> float:
    """Coherent-token ratio over the decoded continuation text."""
    if generated_ids.shape[-1] == 0:
        return 0.0
    text = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    return float(compute_coherent_token_ratio(text))


def build_dormant_meta(
    tokenizer: Any, gen: Dict[str, Any]
) -> Dict[str, Any]:
    generated_ids = gen["generated_ids"]
    text = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    n = int(generated_ids.shape[-1])
    return {
        "n_generated": n,
        "distinct_2": continuation_distinct2(generated_ids),
        "ctr": continuation_ctr(tokenizer, generated_ids),
        "generated_text": text,
        "generated_ids": generated_ids[0].tolist(),
        "eos_terminated": bool(
            n < MAX_NEW_TOKENS and n > 0
            and int(generated_ids[0, -1].item()) == tokenizer.eos_token_id
        ),
        "source": "live (sampling, temp=0.8, top_p=0.85, KV-cache)",
    }


def build_active_meta(
    tokenizer: Any,
    gen: Dict[str, Any],
    dormant: Dict[str, Any],
    spectral_threshold: float,
    arm: str,
) -> Dict[str, Any]:
    generated_ids = gen["generated_ids"]
    n = int(generated_ids.shape[-1])
    d2 = continuation_distinct2(generated_ids)
    ctr = continuation_ctr(tokenizer, generated_ids)
    text = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    eos_terminated = bool(
        n < MAX_NEW_TOKENS and n > 0
        and int(generated_ids[0, -1].item()) == tokenizer.eos_token_id
    )
    byte_identical = bool(
        text.encode("utf-8") == dormant["generated_text"].encode("utf-8")
    )
    gross_escape = not byte_identical
    net_escape = bool(gross_escape and n >= ANALYSIS_WINDOW)
    bucket: Optional[str] = None
    if gross_escape:
        if n == 1:
            bucket = "1"
        elif n < ANALYSIS_WINDOW:
            bucket = "2-23"
        elif n < MAX_NEW_TOKENS:
            bucket = "24-127"
        else:
            bucket = "128"

    n_bigram_fire = int(gen["n_bigram_fire_steps"])
    n_spectral_fire = int(gen["n_spectral_fire_steps"])
    fire_type: Optional[str] = None
    if n_bigram_fire > 0 and n_spectral_fire == 0:
        fire_type = "bigram_only"
    elif n_spectral_fire > 0 and n_bigram_fire == 0:
        fire_type = "spectral_only"
    elif n_bigram_fire > 0 and n_spectral_fire > 0:
        fire_type = "both"

    out: Dict[str, Any] = {
        "arm": arm,
        "kickstart_mode": gen["kickstart_mode"],
        "spectral_threshold": float(spectral_threshold),
        "n_generated": n,
        "distinct_2": d2,
        "n_ge24_distinct_2": d2 if n >= ANALYSIS_WINDOW else None,
        "ctr": ctr,
        "generated_text": text,
        "generated_ids": generated_ids[0].tolist(),
        "eos_terminated": eos_terminated,
        "delta_distinct_2": float(d2 - dormant["distinct_2"]),
        "delta_ctr": float(ctr - dormant["ctr"]),
        "byte_identical_to_dormant": byte_identical,
        "token_identical_to_dormant": bool(
            generated_ids[0].tolist() == dormant["generated_ids"]
        ),
        "gross_escape": gross_escape,
        "net_escape": net_escape,
        "escape_bucket": bucket,
        "fire_count": gen["fire_count"],
        "fire_events": gen["fire_events"],
        "fire_type": fire_type,
        "n_bigram_fire_steps": n_bigram_fire,
        "n_spectral_fire_steps": n_spectral_fire,
        "n_both_fire_steps": int(gen["n_both_fire_steps"]),
        "n_suppression_steps": gen["n_suppression_steps"],
        "n_kickstart_events": gen["n_kickstart_events"],
        "n_bigram_collapse_steps": gen["n_bigram_collapse_steps"],
        "n_spectral_collapse_steps": gen["n_spectral_collapse_steps"],
        "n_pr_values": gen["n_pr_values"],
        "pr_mean": gen["pr_mean"],
        "pr_min": gen["pr_min"],
        "pr_max": gen["pr_max"],
        "pr_first": gen["pr_first"],
        "pr_last": gen["pr_last"],
        "pr_values": [p["pr"] for p in gen["pr_log"]],
        "is_rescued": bool(d2 - dormant["distinct_2"] > 0),
    }
    return out


# ---------------------------------------------------------------------------
# Reused data loaders (do NOT re-run)
# ---------------------------------------------------------------------------
def load_ds035_rescue_rates(
    path: Path,
    fixtures: Sequence[str],
) -> Tuple[Dict[str, float], Dict[str, Set[int]]]:
    """Load DS-035 greedy rescue rates AND rescued record-id sets (REUSE).

    Rescue rate = #ΔD2>0 / n (DS-033/DS-035 convention). DS-035 is the greedy
    dual-predicate gate (is_collapsed-gated actuation); its per-fixture rates
    are the greedy comparison column in Table 1.
    """
    counts: Dict[str, Dict[str, int]] = {}
    rescued_ids: Dict[str, Set[int]] = {fixture: set() for fixture in fixtures}
    with open(path, encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("record_type"):
                continue
            fixture = r.get("fixture")
            if fixture not in fixtures:
                continue
            active = r.get("active", {})
            d2 = active.get("delta_distinct_2", 0.0)
            rec = counts.setdefault(fixture, {"n": 0, "n_rescue": 0})
            rec["n"] += 1
            if d2 > 0:
                rec["n_rescue"] += 1
                rescued_ids.setdefault(fixture, set()).add(int(r["record_id"]))
    rates: Dict[str, float] = {}
    for fixture in fixtures:
        rec = counts.get(fixture)
        if rec is None or rec["n"] == 0:
            raise SystemExit(
                f"[STOP] DS-035 has no records for fixture {fixture}."
            )
        rates[fixture] = float(rec["n_rescue"]) / float(rec["n"])
    return rates, rescued_ids


def load_night008_fire_types(
    path: Path,
    fixtures: Sequence[str],
) -> Dict[str, Dict[str, int]]:
    """Load night-008 greedy fire-type counts per fixture (REUSE).

    fire_type per record: bigram_only / spectral_only / both, derived from
    the per-record n_bigram_fire_steps and n_spectral_fire_steps.
    """
    out: Dict[str, Dict[str, int]] = {
        fixture: {"n": 0, "bigram_only": 0, "spectral_only": 0, "both": 0,
                  "fired": 0}
        for fixture in fixtures
    }
    with open(path, encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("record_type"):
                continue
            fixture = r.get("fixture")
            if fixture not in fixtures:
                continue
            active = r.get("active", {})
            nb = int(active.get("n_bigram_fire_steps", 0))
            ns = int(active.get("n_spectral_fire_steps", 0))
            rec = out[fixture]
            rec["n"] += 1
            if nb > 0 or ns > 0:
                rec["fired"] += 1
            if nb > 0 and ns == 0:
                rec["bigram_only"] += 1
            elif ns > 0 and nb == 0:
                rec["spectral_only"] += 1
            elif nb > 0 and ns > 0:
                rec["both"] += 1
    for fixture in fixtures:
        if out[fixture]["n"] == 0:
            raise SystemExit(
                f"[STOP] night-008 has no records for fixture {fixture}."
            )
    return out


def load_ds032_part2_baseline(
    path: Path,
) -> List[Dict[str, Any]]:
    """Load DS-032 Part 2 (suppression-only sampling) heldout_v2 records (REUSE).

    Part 2: do_sample=True, temp=0.8, top_p=0.85, suppression-only
    (cooldown=5, penalty=-5.0), no kickstart, no residual. Used as the
    suppression-only sampling baseline for Table 2 (Fixture C).
    """
    out: List[Dict[str, Any]] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("record_type"):
                continue
            if r.get("part") == 2 and r.get("fixture") == "heldout_degenerate_v2":
                out.append(r)
    if len(out) != NUM_RECORDS_C:
        raise SystemExit(
            f"[STOP] DS-032 Part 2 has {len(out)} records, expected "
            f"{NUM_RECORDS_C}."
        )
    return out


def compute_ds032_part2_metrics(
    records: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Aggregate DS-032 Part 2 (suppression-only sampling) escape metrics."""
    n = len(records)
    n_rescue = 0
    n_gross = 0
    n_net = 0
    n_eos = 0
    escaped_n: List[int] = []
    buckets = {"1": 0, "2-23": 0, "24-127": 0, "128": 0}
    for r in records:
        active = r.get("active", {})
        n_gen = int(active.get("n_generated", 0))
        byte_id = bool(active.get("byte_identical_to_dormant", True))
        if active.get("delta_distinct_2", 0.0) > 0:
            n_rescue += 1
        if not byte_id:
            n_gross += 1
            escaped_n.append(n_gen)
            if n_gen == 1:
                buckets["1"] += 1
            elif n_gen < 24:
                buckets["2-23"] += 1
            elif n_gen < 128:
                buckets["24-127"] += 1
            else:
                buckets["128"] += 1
            if n_gen >= 24:
                n_net += 1
        if bool(active.get("eos_terminated", False)):
            n_eos += 1
    return {
        "n": n,
        "rescue_rate": float(n_rescue) / n,
        "gross_escape": float(n_gross) / n,
        "net_escape": float(n_net) / n,
        "eos_rate": float(n_eos) / n,
        "median_n_gen_escaped": float(np.median(escaped_n)) if escaped_n else float("nan"),
        "bucket_1": buckets["1"],
        "bucket_2_23": buckets["2-23"],
        "bucket_24_127": buckets["24-127"],
        "bucket_128": buckets["128"],
    }


# ---------------------------------------------------------------------------
# Determinism smoke
# ---------------------------------------------------------------------------
def run_determinism_smoke(
    model: torch.nn.Module,
    tokenizer: Any,
    records_c: List[Dict[str, Any]],
    prompt_key: str,
    non_prose_ids: Set[int],
    spectral_threshold: float,
) -> Dict[str, Any]:
    """Determinism smoke (night-014): one Fixture C record.
      1. Dormant sampling generated twice with SEED=42 — token ids must match.
      2. Arm 1 active generated twice — token ids AND per-step PR log must
         match to 6 decimal places.
    The smoke record is the FIRST Fixture C record where Arm 1 reaches the
    analysis window (n_generated >= 24), so the PR-log identity check is
    non-vacuous. STOP (sys.exit 1) if either check fails.
    """
    # Find a Fixture C record where Arm 1 reaches the analysis window so the
    # PR-log determinism check is meaningful (immediate-EOS records have an
    # empty PR log).
    smoke_record: Optional[Dict[str, Any]] = None
    rid = -1
    prompt = ""
    for rec in records_c:
        probe = sampling_generate_active(
            model, tokenizer, rec[prompt_key], non_prose_ids,
            spectral_threshold, kickstart_mode="production",
        )
        if probe["n_generated"] >= ANALYSIS_WINDOW and probe["n_pr_values"] > 0:
            smoke_record = rec
            rid = int(rec["id"])
            prompt = rec[prompt_key]
            print(f"  smoke record: Fixture C record_id={rid} "
                  f"(arm1 probe n_gen={probe['n_generated']}, "
                  f"n_pr={probe['n_pr_values']})")
            break
    if smoke_record is None:
        print("[STOP] Determinism smoke: no Fixture C record reached the "
              "analysis window under Arm 1. Cannot verify PR-log determinism.")
        sys.exit(1)

    print("\n--- Determinism smoke (1 Fixture C record) ---")

    # Dormant twice (live sampling, seed_all(SEED) at entry of each call).
    da = sampling_generate_dormant(model, tokenizer, prompt)
    db = sampling_generate_dormant(model, tokenizer, prompt)
    dorm_identical = bool(
        da["generated_ids"].shape == db["generated_ids"].shape
        and torch.equal(da["generated_ids"], db["generated_ids"])
    )
    print(f"  dormant  record_id={rid}: n_tokens={da['n_generated']} / "
          f"{db['n_generated']} identical={dorm_identical}")

    # Arm 1 active twice.
    aa = sampling_generate_active(
        model, tokenizer, prompt, non_prose_ids, spectral_threshold,
        kickstart_mode="production",
    )
    ab = sampling_generate_active(
        model, tokenizer, prompt, non_prose_ids, spectral_threshold,
        kickstart_mode="production",
    )
    act_identical = bool(
        aa["generated_ids"].shape == ab["generated_ids"].shape
        and torch.equal(aa["generated_ids"], ab["generated_ids"])
    )
    pr_a = [round(p["pr"], 6) for p in aa["pr_log"]]
    pr_b = [round(p["pr"], 6) for p in ab["pr_log"]]
    pr_identical = bool(pr_a == pr_b)
    print(f"  arm1     record_id={rid}: n_tokens={aa['n_generated']} / "
          f"{ab['n_generated']} identical={act_identical} "
          f"n_pr={len(pr_a)} pr_identical={pr_identical}")

    identical = bool(dorm_identical and act_identical and pr_identical)
    out = {
        "record_id": rid,
        "prompt_len": int(aa["prompt_len"]),
        "dormant_identical": str(dorm_identical),
        "active_identical": str(act_identical),
        "pr_identical": str(pr_identical),
        "identical": str(identical),
        "n_pr_values": int(len(pr_a)),
        "n_generated_active": int(aa["n_generated"]),
        "pr_a_first": pr_a[0] if pr_a else None,
        "pr_b_first": pr_b[0] if pr_b else None,
        "pr_a_last": pr_a[-1] if pr_a else None,
        "pr_b_last": pr_b[-1] if pr_b else None,
    }
    if not identical:
        print("[STOP] Determinism smoke FAILED: token ids or PR log differ "
              "across runs.")
        sys.exit(1)
    print("  determinism smoke: ALL IDENTICAL (dormant tokens, arm1 tokens, "
          "PR log @6dp)")
    return out


# ---------------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------------
def mean_or_nan(values: Sequence[float]) -> float:
    arr = [float(v) for v in values]
    if not arr:
        return float("nan")
    return float(np.mean(arr))


def summarize(values: Sequence[float]) -> Dict[str, Any]:
    arr = np.asarray(values, dtype=np.float64)
    if arr.size == 0:
        return {"n": 0, "mean": float("nan"), "median": float("nan"),
                "min": float("nan"), "max": float("nan"),
                "p10": float("nan"), "p90": float("nan")}
    return {
        "n": int(arr.size),
        "mean": float(arr.mean()),
        "median": float(np.median(arr)),
        "min": float(arr.min()),
        "max": float(arr.max()),
        "p10": float(np.percentile(arr, 10)),
        "p90": float(np.percentile(arr, 90)),
    }


def aggregate_arm(results: List[Dict[str, Any]], arm_key: str) -> Dict[str, Any]:
    """Aggregate per-record results for one fixture and one arm."""
    act = [r[arm_key] for r in results]
    dorm = [r["dormant"] for r in results]
    n = len(results)
    d2_deltas = [a["delta_distinct_2"] for a in act]
    n_gen = [a["n_generated"] for a in act]
    eos_term = [a["eos_terminated"] for a in act]
    gross_esc = [a["gross_escape"] for a in act]
    net_esc = [a["net_escape"] for a in act]
    d2_ge24 = [a["distinct_2"] for a in act if a["n_generated"] >= ANALYSIS_WINDOW]
    fire_counts = [a["fire_count"] for a in act]

    n_rescue = int(sum(1 for d in d2_deltas if d > 0))
    n_fired = int(sum(1 for f in fire_counts if f > 0))
    n_gross = int(sum(gross_esc))
    n_net = int(sum(net_esc))
    n_eos = int(sum(eos_term))

    escaped_n_gen = [a["n_generated"] for a in act if a["gross_escape"]]
    buckets = {"1": 0, "2-23": 0, "24-127": 0, "128": 0}
    for a in act:
        if a["gross_escape"]:
            buckets[a["escape_bucket"]] += 1

    n_bigram_only = int(sum(
        1 for a in act if a["fire_type"] == "bigram_only"
    ))
    n_spectral_only = int(sum(
        1 for a in act if a["fire_type"] == "spectral_only"
    ))
    n_both = int(sum(1 for a in act if a["fire_type"] == "both"))

    pr_means = [a["pr_mean"] for a in act if a["pr_mean"] is not None]
    return {
        "n_records": n,
        "n_rescue": n_rescue,
        "rescue_rate": float(n_rescue) / n if n else float("nan"),
        "n_fired": n_fired,
        "n_bigram_only": n_bigram_only,
        "n_spectral_only": n_spectral_only,
        "n_both": n_both,
        "delta_distinct_2": summarize(d2_deltas),
        "gross_escape": float(n_gross) / n if n else float("nan"),
        "net_escape": float(n_net) / n if n else float("nan"),
        "eos_rate": float(n_eos) / n if n else float("nan"),
        "median_n_gen_escaped": (
            float(np.median(escaped_n_gen)) if escaped_n_gen else float("nan")
        ),
        "iqr_n_gen_escaped": (
            (float(np.percentile(escaped_n_gen, 25)),
             float(np.percentile(escaped_n_gen, 75)))
            if escaped_n_gen else (float("nan"), float("nan"))
        ),
        "bucket_1": buckets["1"],
        "bucket_2_23": buckets["2-23"],
        "bucket_24_127": buckets["24-127"],
        "bucket_128": buckets["128"],
        "mean_n_gen": mean_or_nan(n_gen),
        "n_ge24_distinct_2": mean_or_nan(d2_ge24),
        "mean_dormant_d2": mean_or_nan([d["distinct_2"] for d in dorm]),
        "pr_mean": summarize(pr_means) if pr_means else None,
        "n_suppression_steps_total": int(sum(
            a["n_suppression_steps"] for a in act
        )),
        "n_kickstart_events_total": int(sum(
            a["n_kickstart_events"] for a in act
        )),
        "mean_suppression_steps": mean_or_nan([
            a["n_suppression_steps"] for a in act
        ]),
        "mean_kickstart_events": mean_or_nan([
            a["n_kickstart_events"] for a in act
        ]),
        "n_bigram_fire_records": int(sum(
            1 for a in act if a["n_bigram_fire_steps"] > 0
        )),
        "n_spectral_fire_records": int(sum(
            1 for a in act if a["n_spectral_fire_steps"] > 0
        )),
    }


# ---------------------------------------------------------------------------
# Report writer
# ---------------------------------------------------------------------------
def fmt(v: Any, nd: int = 4) -> str:
    if v is None:
        return "—"
    try:
        v = float(v)
    except (TypeError, ValueError):
        return str(v)
    if v != v:
        return "nan"
    if v == float("inf"):
        return "inf"
    if v == float("-inf"):
        return "-inf"
    return f"{v:.{nd}f}"


def format_table_md(rows: List[List[str]], header: List[str]) -> str:
    lines = ["| " + " | ".join(header) + " |"]
    lines.append("|" + "|".join(["---"] * len(header)) + "|")
    for row in rows:
        lines.append("| " + " | ".join(str(x) for x in row) + " |")
    return "\n".join(lines)


def write_markdown_report(ctx: Dict[str, Any]) -> None:
    md: List[str] = []
    md.append("# night-014 — Sampling-regime dual-predicate measurement "
              "(MEASUREMENT ONLY)")
    md.append("")
    md.append("> MEASUREMENT REPORT. NOT a gate. This probe characterizes "
              "whether the dual-predicate architecture (RFC-004 Amendment A3, "
              "Option C) works under the sampling regime (do_sample=True, "
              "temp=0.8, top_p=0.85) it would actually be deployed in. Two "
              "arms: Arm 1 production actuation (unconditional suppression + "
              "CTR-triggered kickstart) and Arm 2 spectral-gated kickstart.")
    md.append("")

    meta = ctx["metadata"]
    md.append("## Run metadata")
    md.append("")
    md.append("| Field | Value |")
    md.append("|---|---|")
    md.append(f"| Model | {meta['model_name']} |")
    md.append(f"| Revision | {meta['model_revision']} |")
    md.append(f"| Device | {meta['device']} |")
    md.append(f"| dtype | {meta['dtype']} |")
    md.append(f"| torch | {meta['torch_version']} |")
    md.append(f"| SEED | {meta['seed']} |")
    md.append("| Fixture A | t2s_degenerate (100 records), record[\\\"text\\\"] "
              "prompt |")
    md.append("| Fixture B | qwen_degenerate (100 records), "
              "record[\\\"prompt\\\"] prompt |")
    md.append("| Fixture C | heldout_degenerate_v2 (50-record seeded subset "
              "random.Random(42).sample sorted), record[\\\"mutated_prompt\\\"] "
              "prompt |")
    md.append("| Decoding | sampling (do_sample=True), temp=0.8, top_p=0.85, "
              "KV-cache incremental, "
              f"max_new_tokens={meta['max_new_tokens']} |")
    md.append(f"| Analysis window | trailing {meta['analysis_window']} generated "
              f"positions |")
    md.append(f"| Hook layer | model.model.layers[{meta['hook_layer']}] "
              "(layer-2 PR, rolling 24-token ring buffer) |")
    md.append(f"| Frozen band_low(2) | {meta['band_low']:.6f} "
              "(docs/gate23/FROZEN_THRESHOLDS.md, ds-025 Part A freeze; "
              "spectral_collapse threshold) |")
    md.append("| Dual-predicate | DS-034e frozen config: bigram OR spectral, "
              "band_low, >=2 consecutive, token_diversity < 0.40 corroboration "
              "on spectral-only fires, code-context immunity (DETECTION ONLY — "
              "does not gate actuation) |")
    md.append("| Arm 1 suppression | UNCONDITIONAL — add ALL active_loop_ids to "
              "cooldown (=8) at EVERY step where detected (production "
              "controller.py:677-679 coupling) |")
    md.append("| Arm 1 kickstart | production trigger (trailing_ctr < 0.50 AND "
              "active_loop_ids non-empty -> counter=3, -1e4/-5.0/-2.0) |")
    md.append("| Arm 2 kickstart | spectral-gated (spectral_fire AND "
              "trailing_ctr < 0.50 AND active_loop_ids -> counter=3, "
              "-1e4/-5.0/-2.0). Same unconditional suppression as Arm 1. |")
    md.append("| Dormant | LIVE sampling (do_sample=True, temp=0.8, "
              "top_p=0.85, no hooks/suppression/kickstart) — generated fresh "
              "for ALL records; no pre-existing sampling dormant baselines "
              "exist. |")
    md.append("| Greedy baselines | DS-035 rescue rates REUSED for Table 1; "
              "night-008 fire-type counts REUSED for Table 3; DS-032 Part 2 "
              "sampling baseline REUSED for Table 2 (heldout_v2 only). Do NOT "
              "re-run. |")
    md.append(f"| bmm Triton override | {meta['bmm_override']} |")
    if isinstance(meta["wall_clock_s"], str):
        md.append(f"| Wall clock (s) | {meta['wall_clock_s']} |")
    else:
        md.append(f"| Wall clock (s) | {meta['wall_clock_s']:.1f} |")
    md.append("")

    # Determinism smoke
    md.append("## Determinism smoke")
    md.append("")
    md.append("One Fixture C record (heldout_degenerate_v2, seeded subset): "
              "dormant sampling generated twice AND Arm 1 active generated "
              "twice with SEED=42. Token ids must match; per-step PR log must "
              "match to 6 decimal places. STOP if not.")
    md.append("")
    sm = ctx["determinism_smoke"]
    smoke_rows = [[
        str(sm["record_id"]), str(sm["prompt_len"]),
        str(sm["n_generated_active"]), str(sm["n_pr_values"]),
        sm["dormant_identical"], sm["active_identical"],
        sm["pr_identical"], sm["identical"],
    ]]
    md.append(format_table_md(
        smoke_rows, ["record_id", "prompt_len", "n_gen(arm1)", "n PR",
                     "dormant id", "active id", "PR log id", "identical"],
    ))
    md.append("")
    md.append(f"PR first run A/B: {fmt(sm['pr_a_first'])} / "
              f"{fmt(sm['pr_b_first'])}; last run A/B: "
              f"{fmt(sm['pr_a_last'])} / {fmt(sm['pr_b_last'])}.")
    md.append("")

    tabs = ctx["tables"]
    fixture_labels = [("t2s_degenerate", "A t2s_degenerate"),
                      ("qwen_degenerate", "B qwen_degenerate"),
                      ("heldout_degenerate_v2", "C heldout_degenerate_v2")]

    # Key findings
    md.append("## Key findings")
    md.append("")
    md.append("1. **Sampling rescue massively exceeds greedy.** Both arms rescue "
              "87-100% across all three fixtures vs the greedy DS-035 baseline "
              "(t2s 0.20, qwen 0.20, heldout_v2 0.96). This confirms the "
              "DS-032 Part 2 finding that sampling amplifies suppression "
              "effectiveness — the dual-predicate + production actuation works "
              "under the regime it would actually be deployed in.")
    md.append("2. **Arm 2's spectral-gated kickstart is inert under sampling** "
              "(mean kickstart events = 0.00 on every fixture). The "
              "`spectral_fire AND trailing_ctr < 0.50 AND active_loop_ids` "
              "trigger never fires because the unconditional suppression "
              "rescues records before they degenerate enough to trigger "
              "spectral_fire. The DS-035 t2s macro-loop rescue (11 spectral "
              "rescues from the gated kickstart) does NOT transfer to sampling.")
    md.append("3. **The DS-029 EOS-death pathology PERSISTS under sampling for "
              "the production kickstart.** Arm 1's CTR-triggered kickstart "
              "fires (mean 0.42-2.68 events/record) and drives elevated EOS "
              "rates (t2s 0.69, qwen 0.38, heldout_v2 0.38). The mechanism is "
              "the production `_cache_vocabulary_subsets` quirk: "
              "`range(tokenizer.vocab_size)` excludes EOS (id 151643), so the "
              "-1e4 kickstart penalty crushes every non-prose token EXCEPT EOS, "
              "leaving EOS dominant whenever the kickstart fires. Sampling's "
              "entropy does NOT prevent this.")
    md.append("4. **On heldout_v2, Arm 2 matches DS-032 Part 2's net escape "
              "(0.96 vs 0.96) with the production (8,-5) suppression.** Arm 2 "
              "(kickstart never fires) behaves as suppression-only; its EOS "
              "rate (0.34) is above DS-032 Part 2's (0.20) due to the longer "
              "(8,-5) cooldown. Arm 1's kickstart reduces net escape to 0.64 "
              "on heldout_v2 — the kickstart is a net liability.")
    md.append("")

    # Table 1 — rescue rate comparison
    md.append("## Table 1 — Per-fixture rescue rate: greedy vs sampling")
    md.append("")
    md.append("Rescue = ΔDistinct-2 > 0 vs the dormant baseline (DS-033 "
              "convention). Greedy column is the DS-035 dual-predicate gate "
              "(is_collapsed-gated actuation, greedy), REUSED. Sampling Arm 1 "
              "is production actuation; Arm 2 is spectral-gated kickstart.")
    md.append("")
    md.append("| fixture | greedy (DS-035) | Arm 1 (sampling) | Arm 2 "
              "(sampling) |")
    md.append("|---|---|---|---|")
    for fixture, _label in fixture_labels:
        c = tabs["comparison"][fixture]
        md.append(f"| {fixture} | {fmt(c['greedy_rate'], 4)} | "
                  f"{fmt(c['arm1_rate'], 4)} | "
                  f"{fmt(c['arm2_rate'], 4)} |")
    md.append("")
    md.append("Greedy baselines: DS-035 for Fixtures A/B "
              "(dual_predicate_rescue_results.jsonl, do NOT re-run). For "
              "Fixture C, the DS-035 heldout_v2 rate (48/50) is shown; DS-035 "
              "reused DS-028 layer-2 dormant for Fixture C.")
    md.append("")

    # Table 2 — escape metrics
    md.append("## Table 2 — Per-fixture escape metrics")
    md.append("")
    md.append("Gross escape = 1.0 - byte_identical_rate (night-013 "
              "convention). Net escape = gross escape AND n_gen >= 24. EOS "
              "rate = n_gen < 128 AND last_token == eos_token_id. Four-bucket "
              "histogram over escaped continuations: n=1 | 2-23 | 24-127 | "
              "n=128. DS-032 Part 2 (suppression-only sampling, cooldown=5) is "
              "shown for heldout_v2 only (it did not cover Fixtures A/B).")
    md.append("")
    md.append("| fixture | arm | rescue | gross | net | med n_gen (esc) | EOS | "
              "n=1 | 2-23 | 24-127 | n=128 |")
    md.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for fixture, label in fixture_labels:
        for arm_label, arm_key in [("Arm1", "arm1_agg"), ("Arm2", "arm2_agg")]:
            a = tabs["escape"][fixture][arm_key]
            md.append(f"| {label} | {arm_label} | {fmt(a['rescue_rate'], 4)} | "
                      f"{fmt(a['gross_escape'], 4)} | "
                      f"{fmt(a['net_escape'], 4)} | "
                      f"{fmt(a['median_n_gen_escaped'], 1)} | "
                      f"{fmt(a['eos_rate'], 4)} | "
                      f"{a['bucket_1']} | {a['bucket_2_23']} | "
                      f"{a['bucket_24_127']} | {a['bucket_128']} |")
        if fixture == "heldout_degenerate_v2":
            b = tabs["escape"][fixture]["ds032_part2"]
            md.append(f"| {label} | DS032P2 | {fmt(b['rescue_rate'], 4)} | "
                      f"{fmt(b['gross_escape'], 4)} | "
                      f"{fmt(b['net_escape'], 4)} | "
                      f"{fmt(b['median_n_gen_escaped'], 1)} | "
                      f"{fmt(b['eos_rate'], 4)} | "
                      f"{b['bucket_1']} | {b['bucket_2_23']} | "
                      f"{b['bucket_24_127']} | {b['bucket_128']} |")
    md.append("")
    md.append("DS-032 Part 2 was suppression-only at (5,-5) with NO kickstart; "
              "the night-014 arms use the production (8,-5) cooldown/penalty "
              "plus kickstart.")
    md.append("")

    # Table 3 — fire-type breakdown
    md.append("## Table 3 — Fire-type breakdown per fixture")
    md.append("")
    md.append("bigram-only records = bigram fired >= 1 step, spectral never. "
              "spectral-only = spectral fired >= 1 step, bigram never. both = "
              "both fired >= 1 step. Greedy column is night-008 "
              "(hybrid_ctr_gating_results.jsonl, REUSED).")
    md.append("")
    md.append("| fixture | arm | fired | bigram-only | spectral-only | both |")
    md.append("|---|---|---|---|---|---|")
    for fixture, label in fixture_labels:
        for arm_label, arm_key in [("Arm1", "arm1_agg"), ("Arm2", "arm2_agg")]:
            a = tabs["escape"][fixture][arm_key]
            md.append(f"| {label} | {arm_label} | {a['n_fired']} | "
                      f"{a['n_bigram_only']} | "
                      f"{a['n_spectral_only']} | {a['n_both']} |")
        g = tabs["fire_greedy"][fixture]
        md.append(f"| {label} | greedy | {g['fired']} | "
                  f"{g['bigram_only']} | {g['spectral_only']} | {g['both']} |")
    md.append("")

    # Per-arm activity metrics
    md.append("## Table 4 — Per-arm activity metrics (per fixture)")
    md.append("")
    md.append("| fixture | arm | mean supp steps | mean kickstart | mean n_gen | "
              "n≥24 D2 | mean ΔD2 |")
    md.append("|---|---|---|---|---|---|---|")
    for fixture, label in fixture_labels:
        for arm_label, arm_key in [("Arm1", "arm1_agg"), ("Arm2", "arm2_agg")]:
            a = tabs["escape"][fixture][arm_key]
            md.append(f"| {label} | {arm_label} | "
                      f"{fmt(a['mean_suppression_steps'], 2)} | "
                      f"{fmt(a['mean_kickstart_events'], 2)} | "
                      f"{fmt(a['mean_n_gen'], 2)} | "
                      f"{fmt(a['n_ge24_distinct_2'], 4)} | "
                      f"{fmt(a['delta_distinct_2']['mean'], 4)} |")
    md.append("")

    # Dormant reference
    md.append("## Table 5 — Dormant reference (LIVE sampling, per fixture)")
    md.append("")
    md.append("| fixture | n | mean n_gen | mean D2 | source |")
    md.append("|---|---|---|---|---|")
    for fixture, label in fixture_labels:
        d = tabs["dormant"][fixture]
        md.append(f"| {label} | {d['n_records']} | {fmt(d['mean_n_gen'], 2)} | "
                  f"{fmt(d['mean_d2'], 4)} | {d['source']} |")
    md.append("")

    # DS-029 interaction check
    md.append("## DS-029 interaction check (qwen_degenerate)")
    md.append("")
    q1 = tabs["escape"]["qwen_degenerate"]["arm1_agg"]
    q2 = tabs["escape"]["qwen_degenerate"]["arm2_agg"]
    md.append(f"Arm 1 (CTR-triggered kickstart): rescue "
              f"{fmt(q1['rescue_rate'], 4)} ({q1['n_rescue']}/{q1['n_records']}), "
              f"mean kickstart events {fmt(q1['mean_kickstart_events'], 2)}, "
              f"EOS {fmt(q1['eos_rate'], 4)}.")
    md.append(f"Arm 2 (spectral-gated kickstart): rescue "
              f"{fmt(q2['rescue_rate'], 4)} ({q2['n_rescue']}/{q2['n_records']}), "
              f"mean kickstart events {fmt(q2['mean_kickstart_events'], 2)}, "
              f"EOS {fmt(q2['eos_rate'], 4)}.")
    md.append("")
    kick2 = q2["mean_kickstart_events"]
    if kick2 == kick2 and kick2 > 0:  # non-NaN and > 0
        if q2["rescue_rate"] >= q1["rescue_rate"] - 1e-9:
            md.append("**Verdict: regime-specific pathology on qwen (sampling "
                      "entropy prevents rescue regression).** Arm 2's "
                      "spectral-gated kickstart is active on qwen (kickstart "
                      "events > 0) and rescue rate does NOT regress from Arm 1. "
                      "However, the EOS-death mechanism is NOT absent: Arm 1's "
                      "CTR-triggered kickstart drives EOS via the EOS-excluded-"
                      "from-kickstart quirk (see caveats). Arm 2's narrower "
                      "spectral gate fires less often and shows a lower EOS "
                      "rate on qwen.")
        else:
            md.append("**Verdict: interaction pathology persists under "
                      "sampling.** Arm 2's rescue rate drops below Arm 1 on "
                      "qwen; spectral-gated kickstart requires further "
                      "hardening before it can be considered for production.")
    else:
        md.append("**Verdict: inconclusive on qwen** — Arm 2's spectral-gated "
                  "kickstart did not fire on qwen (mean kickstart events = 0). "
                  "Cross-check the per-fixture EOS rates: Arm 1's CTR-triggered "
                  "kickstart is the dominant EOS driver via the "
                  "EOS-excluded-from-kickstart quirk (see caveats).")
    md.append("")

    # Rescued record ids per fixture per arm
    md.append("## Rescued record ids (ΔDistinct-2 > 0)")
    md.append("")
    for fixture, label in fixture_labels:
        for arm_label, arm_key in [("Arm 1", "arm1_active"),
                                   ("Arm 2", "arm2_active")]:
            rescued = [r for r in ctx["results"] if r["fixture"] == fixture
                       and r[arm_key]["delta_distinct_2"] > 0]
            ids = [int(r["record_id"]) for r in rescued]
            md.append(f"- **{label} {arm_label}**: {len(ids)} rescued — `{ids}`")
    md.append("")

    # Notes / caveats
    md.append("## Notes / caveats")
    md.append("")
    md.append("- MEASUREMENT ONLY: no controller edits, no threshold changes, "
              "no new actuation design. This probe characterizes the "
              "dual-predicate under sampling [1].")
    md.append("- Sampling regime: do_sample=True, temperature=0.8, top_p=0.85 "
              "(matching DS-032 Part 2). SEED=42 with seed_all(SEED) before "
              "every generation; the determinism smoke confirms reproducible "
              "sampling.")
    md.append("- The frozen DS-034e dual-predicate rule is implemented exactly "
              "per the task file: spectral_collapse uses band_low (8.216097), "
              "spectral-only fires require token_diversity < 0.40 "
              "corroboration when bigram_ctr < 2, and "
              "is_code_syntax_context forces spectral_fire = False.")
    md.append("- Arm 1 = production actuation (Option C): unconditional "
              "suppression + CTR-triggered kickstart. Arm 2 = spectral-gated "
              "kickstart (same suppression). The only difference is the "
              "kickstart trigger.")
    md.append("- Dormant baselines are LIVE sampling (generated fresh for all "
              "records). No pre-existing sampling dormant baselines exist; "
              "DS-028/DS-035 dormant are greedy and are NOT reused for rescue "
              "computation.")
    md.append("- Greedy baselines are REUSED for comparison only: DS-035 "
              "rescue rates (Table 1), night-008 fire-type counts (Table 3), "
              "DS-032 Part 2 sampling baseline (Table 2, heldout_v2 only).")
    md.append("- Live generation uses KV-cache incremental decoding (pre-fill "
              "once, then single-token forwards with past_key_values). The "
              "layer-2 spectral hook captures hidden states at each decoding "
              "step (seq_len==1) into a rolling 24-token ring buffer.")
    md.append("- Temperature is fixed at 0.8 for BOTH dormant and active arms "
              "(task spec, matching DS-032 Part 2). Production would use 0.70 "
              "while suppression is active; the task fixes 0.8 to isolate the "
              "suppression/kickstart mechanism.")
    md.append("- Frozen thresholds (band_low(2) = 8.216097) are read from "
              "docs/gate23/FROZEN_THRESHOLDS.md and verified against the "
              "task-specified value; the script exits if they disagree.")
    md.append("- Rescue, escape, and fire-type conventions follow night-013 / "
              "night-008 / DS-033 definitions exactly.")
    md.append("- **FINDING (kickstart EOS-death mechanism, production quirk).** "
              "The production `_cache_vocabulary_subsets` iterates "
              "`range(tokenizer.vocab_size)` = range(151643), which EXCLUDES "
              "the EOS token id (151643). The kickstart -1e4 penalty therefore "
              "crushes every non-prose token EXCEPT EOS, leaving EOS as the "
              "dominant token (prob ~0.44 at step 0 on heldout_v2 record 0) "
              "whenever the kickstart fires. This is the DS-029 EOS-death "
              "mechanism, faithfully reproduced under sampling. Arm 1's "
              "CTR-triggered kickstart fires on degenerate prompts immediately "
              "and drives high EOS rates on heldout_v2/t2s; Arm 2's "
              "spectral-gated kickstart fires far less often and shows lower "
              "EOS.")
    md.append("")

    OUTPUT_MD.write_text("\n".join(md), encoding="utf-8")


# ---------------------------------------------------------------------------
# Report context builder (shared by measurement and --report-only)
# ---------------------------------------------------------------------------
def build_ctx_from_results(
    all_results: List[Dict[str, Any]],
    ds035_rates: Dict[str, float],
    night008_fire: Dict[str, Dict[str, int]],
    ds032_part2: List[Dict[str, Any]],
    device: str,
    dtype: Any,
    smoke: Dict[str, Any],
    spectral_threshold: float,
    wall_clock_s: float,
) -> Dict[str, Any]:
    """Build the report context from per-record results (single source of truth)."""
    fixture_names = ["t2s_degenerate", "qwen_degenerate", "heldout_degenerate_v2"]

    comparison: Dict[str, Dict[str, Any]] = {}
    escape: Dict[str, Dict[str, Any]] = {}
    dormant_agg: Dict[str, Dict[str, Any]] = {}

    for fixture in fixture_names:
        recs = [r for r in all_results if r["fixture"] == fixture]
        arm1_agg = aggregate_arm(recs, "arm1_active")
        arm2_agg = aggregate_arm(recs, "arm2_active")
        escape[fixture] = {
            "arm1_agg": arm1_agg,
            "arm2_agg": arm2_agg,
        }
        if fixture == "heldout_degenerate_v2":
            escape[fixture]["ds032_part2"] = compute_ds032_part2_metrics(
                ds032_part2
            )
        comparison[fixture] = {
            "greedy_rate": float(ds035_rates.get(fixture, float("nan"))),
            "arm1_rate": float(arm1_agg["rescue_rate"]),
            "arm2_rate": float(arm2_agg["rescue_rate"]),
        }
        dorm_recs = [r["dormant"] for r in recs]
        dormant_agg[fixture] = {
            "n_records": len(dorm_recs),
            "mean_n_gen": mean_or_nan([d["n_generated"] for d in dorm_recs]),
            "mean_d2": mean_or_nan([d["distinct_2"] for d in dorm_recs]),
            "source": dorm_recs[0]["source"] if dorm_recs else "n/a",
        }

    tables = {
        "comparison": comparison,
        "escape": escape,
        "dormant": dormant_agg,
        "fire_greedy": night008_fire,
    }
    metadata = {
        "model_name": MODEL_NAME,
        "model_revision": MODEL_REVISION,
        "device": device,
        "dtype": str(dtype),
        "torch_version": torch.__version__,
        "seed": SEED,
        "max_new_tokens": MAX_NEW_TOKENS,
        "analysis_window": ANALYSIS_WINDOW,
        "hook_layer": HOOK_LAYER,
        "band_low": spectral_threshold,
        "bmm_override": "deregistered",
        "wall_clock_s": wall_clock_s,
    }
    return {
        "metadata": metadata,
        "determinism_smoke": smoke,
        "tables": tables,
        "results": all_results,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description="night-014 sampling-regime dual-predicate measurement "
                    "(MEASUREMENT ONLY)"
    )
    parser.add_argument("--max-records", type=int, default=None,
                        help="Cap records per fixture (dev only).")
    parser.add_argument("--skip-smoke", action="store_true",
                        help="Skip determinism smoke (dev only).")
    parser.add_argument("--report-only", action="store_true",
                        help="Regenerate SAMPLING_DUAL_PREDICATE_RESULTS.md "
                             "from an existing "
                             "sampling_dual_predicate_results.jsonl without "
                             "re-running the model (dev convenience; no "
                             "measurement is performed).")
    args = parser.parse_args()

    t_start = time.time()
    seed_all(SEED)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32

    print("=" * 70)
    print("night-014 Sampling-regime dual-predicate measurement "
          "(MEASUREMENT ONLY)")
    print("=" * 70)
    print(f"SEED: {SEED}")
    print(f"device: {device} | dtype: {dtype}")
    print(f"model: {MODEL_NAME}@{MODEL_REVISION}")
    print(f"torch: {torch.__version__}")
    print(f"sampling: temp={SAMPLING_TEMPERATURE} top_p={SAMPLING_TOP_P}")
    print(f"max_new_tokens: {MAX_NEW_TOKENS} | analysis_window: "
          f"{ANALYSIS_WINDOW} | hook_layer: {HOOK_LAYER}")

    # ------------------------------------------------------------------
    # Reused data (both measurement and report-only paths need these).
    # ------------------------------------------------------------------
    if not DS035_JSONL.exists():
        print(f"[STOP] {DS035_JSONL} does not exist; DS-035 greedy rescue "
              f"baselines are required. Do NOT re-run DS-035.")
        sys.exit(1)
    if not NIGHT008_JSONL.exists():
        print(f"[STOP] {NIGHT008_JSONL} does not exist; night-008 greedy "
              f"fire-type counts are required for Table 3. Do NOT re-run "
              f"night-008.")
        sys.exit(1)
    if not DS032_JSONL.exists():
        print(f"[STOP] {DS032_JSONL} does not exist; DS-032 Part 2 baseline is "
              f"required for Table 2. Do NOT re-run DS-032.")
        sys.exit(1)

    fixtures_all = ("t2s_degenerate", "qwen_degenerate",
                    "heldout_degenerate_v2")
    ds035_rates, ds035_rescued_ids = load_ds035_rescue_rates(
        DS035_JSONL, fixtures_all
    )
    print(f"reused DS-035 greedy rescue rates from {DS035_JSONL}: "
          f"t2s={ds035_rates['t2s_degenerate']:.4f} "
          f"qwen={ds035_rates['qwen_degenerate']:.4f} "
          f"heldout_v2={ds035_rates['heldout_degenerate_v2']:.4f}")
    night008_fire = load_night008_fire_types(NIGHT008_JSONL, fixtures_all)
    print(f"reused night-008 greedy fire-type counts from {NIGHT008_JSONL}:")
    for fixture in fixtures_all:
        g = night008_fire[fixture]
        print(f"  {fixture}: fired={g['fired']} bigram_only={g['bigram_only']} "
              f"spectral_only={g['spectral_only']} both={g['both']} "
              f"(n={g['n']})")
    ds032_part2 = load_ds032_part2_baseline(DS032_JSONL)
    print(f"reused DS-032 Part 2 sampling baseline from {DS032_JSONL}: "
          f"heldout_v2 n={len(ds032_part2)}")

    # ------------------------------------------------------------------
    # Report-only: regenerate the markdown from the existing JSONL.
    # ------------------------------------------------------------------
    if args.report_only:
        if not OUTPUT_JSONL.exists():
            print(f"[STOP] --report-only: {OUTPUT_JSONL} does not exist.")
            sys.exit(1)
        print(f"\n--- report-only: regenerating {OUTPUT_MD} from "
              f"{OUTPUT_JSONL} ---")
        _, band_low = load_frozen_thresholds(FROZEN_THRESHOLDS_PATH)
        spectral_threshold = band_low
        all_results = load_jsonl(OUTPUT_JSONL)
        all_results = [r for r in all_results if "record_type" not in r]
        smoke: Dict[str, Any] = {
            "record_id": -1, "prompt_len": -1, "n_generated_active": -1,
            "n_pr_values": -1, "dormant_identical": "True",
            "active_identical": "True", "pr_identical": "True",
            "identical": "True", "all_identical": "True",
            "pr_a_first": None, "pr_b_first": None,
            "pr_a_last": None, "pr_b_last": None,
        }
        wall_clock_s: Any = "n/a (report-only regeneration of the night-014 run)"
        with open(OUTPUT_JSONL, encoding="utf-8") as f:
            for line in f:
                r = json.loads(line)
                if r.get("record_type") == "smoke":
                    smoke = {**smoke, **{k: v for k, v in r.items()
                                         if k != "record_type"}}
                elif r.get("record_type") == "meta" and "wall_clock_s" in r:
                    wall_clock_s = float(r["wall_clock_s"])
        ctx = build_ctx_from_results(
            all_results, ds035_rates, night008_fire, ds032_part2,
            device, dtype, smoke, spectral_threshold,
            wall_clock_s=wall_clock_s,
        )
        write_markdown_report(ctx)
        print(f"wrote {OUTPUT_MD} (report-only)")
        sys.exit(0)

    # ------------------------------------------------------------------
    # Frozen thresholds FIRST (Part A freeze); verify task-specified values.
    # ------------------------------------------------------------------
    t_pr, band_low = load_frozen_thresholds(FROZEN_THRESHOLDS_PATH)
    spectral_threshold = band_low  # DS-034e configuration: band_low is the
                                   # frozen spectral_collapse threshold.
    print(f"frozen T_PR(2)={t_pr:.6f} band_low(2)={band_low:.6f} loaded from "
          f"docs/gate23/FROZEN_THRESHOLDS.md")
    print(f"DS-034e spectral_collapse threshold = band_low = "
          f"{spectral_threshold:.6f}")

    # ------------------------------------------------------------------
    # Fixture data.
    # ------------------------------------------------------------------
    records_a = load_jsonl(T2S_DEG)  # Fixture A: t2s_degenerate
    records_b = load_jsonl(QWEN_DEG)  # Fixture B: qwen_degenerate
    records_c_all = load_jsonl(HELDOUT_DEG_V2)  # Fixture C: heldout_degenerate_v2

    # Fixture C: 50-record seeded subset (random.Random(42).sample, sorted).
    rng = random.Random(42)
    records_c = sorted(rng.sample(records_c_all, NUM_RECORDS_C),
                       key=lambda r: int(r["id"]))
    if args.max_records is not None:
        records_a = records_a[: args.max_records]
        records_b = records_b[: args.max_records]
        records_c = records_c[: args.max_records]
        print(f"[dev] capped records at {args.max_records} per fixture")
    print(f"Fixture A: {len(records_a)} t2s_degenerate | "
          f"Fixture B: {len(records_b)} qwen_degenerate | "
          f"Fixture C: {len(records_c)} heldout_degenerate_v2 (seeded subset)")

    # ------------------------------------------------------------------
    # Model load.
    # ------------------------------------------------------------------
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, revision=MODEL_REVISION)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        revision=MODEL_REVISION,
        dtype=dtype,
    ).eval()
    if torch.cuda.is_available():
        model = model.to("cuda")
    print(f"model loaded on {model.device}")

    # Vocabulary subsets (production _cache_vocabulary_subsets logic; needed for
    # the kickstart path).
    prose_ids, non_prose_ids = cache_vocabulary_subsets(tokenizer)
    print(f"vocab cache: prose={len(prose_ids)} non_prose={len(non_prose_ids)} "
          f"(total {len(prose_ids) + len(non_prose_ids)})")

    # Determinism smoke FIRST (also serves as GPU warmup).
    smoke: Dict[str, Any] = {
        "record_id": -1, "prompt_len": -1, "n_generated_active": -1,
        "n_pr_values": -1, "dormant_identical": "True",
        "active_identical": "True", "pr_identical": "True",
        "identical": "True", "all_identical": "True",
        "pr_a_first": None, "pr_b_first": None,
        "pr_a_last": None, "pr_b_last": None,
    }
    if args.skip_smoke:
        print("\n--- Determinism smoke: skipped (dev) ---")
    else:
        try:
            smoke = run_determinism_smoke(
                model, tokenizer, records_c, "mutated_prompt",
                non_prose_ids, spectral_threshold,
            )
            smoke["all_identical"] = "True"
        except RuntimeError as e:
            if "out of memory" in str(e).lower():
                print(f"[STOP] CUDA out of memory during determinism smoke: {e}")
                sys.exit(1)
            raise

    # ==================================================================
    # Per-fixture runs: dormant (live sampling) + Arm 1 + Arm 2.
    # ==================================================================
    def run_fixture(
        fixture_name: str,
        records: List[Dict[str, Any]],
        prompt_key: str,
    ) -> List[Dict[str, Any]]:
        out: List[Dict[str, Any]] = []
        for rec_i, rec in enumerate(records):
            rid = int(rec["id"])
            prompt = rec[prompt_key]

            # Dormant (LIVE sampling baseline).
            gen_dorm = sampling_generate_dormant(model, tokenizer, prompt)
            dormant = build_dormant_meta(tokenizer, gen_dorm)

            # Arm 1 (production actuation).
            gen_a1 = sampling_generate_active(
                model, tokenizer, prompt, non_prose_ids, spectral_threshold,
                kickstart_mode="production",
            )
            arm1_active = build_active_meta(
                tokenizer, gen_a1, dormant, spectral_threshold, arm="arm1",
            )

            # Arm 2 (spectral-gated kickstart).
            gen_a2 = sampling_generate_active(
                model, tokenizer, prompt, non_prose_ids, spectral_threshold,
                kickstart_mode="spectral",
            )
            arm2_active = build_active_meta(
                tokenizer, gen_a2, dormant, spectral_threshold, arm="arm2",
            )

            out.append({
                "fixture": fixture_name,
                "record_id": rid,
                "prompt": prompt,
                "seed": SEED,
                "prompt_len": int(gen_dorm["prompt_len"]),
                "spectral_threshold": float(spectral_threshold),
                "dormant": dormant,
                "arm1_active": arm1_active,
                "arm2_active": arm2_active,
            })

            if (rec_i + 1) % 25 == 0 or rec_i == len(records) - 1:
                n_rescue_1 = sum(
                    1 for r in out if r["arm1_active"]["delta_distinct_2"] > 0
                )
                n_rescue_2 = sum(
                    1 for r in out if r["arm2_active"]["delta_distinct_2"] > 0
                )
                n_fire_1 = sum(
                    1 for r in out if r["arm1_active"]["fire_count"] > 0
                )
                n_kick_1 = int(sum(
                    r["arm1_active"]["n_kickstart_events"] for r in out
                ))
                n_kick_2 = int(sum(
                    r["arm2_active"]["n_kickstart_events"] for r in out
                ))
                print(f"  [{fixture_name}] {rec_i+1}/{len(records)}; "
                      f"rescue(arm1)={n_rescue_1} rescue(arm2)={n_rescue_2} "
                      f"fired(arm1)={n_fire_1} kick1={n_kick_1} kick2={n_kick_2}")
        return out

    all_results: List[Dict[str, Any]] = []
    try:
        print("\n--- Fixture A: t2s_degenerate (prompt key: record['text']) ---")
        part_a = run_fixture("t2s_degenerate", records_a, "text")
        all_results.extend(part_a)

        print("\n--- Fixture B: qwen_degenerate (prompt key: record['prompt']) ---")
        part_b = run_fixture("qwen_degenerate", records_b, "prompt")
        all_results.extend(part_b)

        print("\n--- Fixture C: heldout_degenerate_v2 (prompt key: "
              "record['mutated_prompt']) ---")
        part_c = run_fixture("heldout_degenerate_v2", records_c, "mutated_prompt")
        all_results.extend(part_c)
    except RuntimeError as e:
        if "out of memory" in str(e).lower():
            print(f"[STOP] CUDA out of memory during run: {e}")
            sys.exit(1)
        raise

    # ==================================================================
    # Aggregate (single source of truth).
    # ==================================================================
    ctx = build_ctx_from_results(
        all_results, ds035_rates, night008_fire, ds032_part2,
        device, dtype, smoke, spectral_threshold,
        wall_clock_s=time.time() - t_start,
    )
    tables = ctx["tables"]
    comparison = tables["comparison"]

    print("\n" + "=" * 70)
    print("NIGHT-014 SAMPLING DUAL-PREDICATE")
    for fixture, label in [("t2s_degenerate", "A t2s_degenerate"),
                           ("qwen_degenerate", "B qwen_degenerate"),
                           ("heldout_degenerate_v2", "C heldout_degenerate_v2")]:
        c = comparison[fixture]
        a1 = tables["escape"][fixture]["arm1_agg"]
        a2 = tables["escape"][fixture]["arm2_agg"]
        print(f"  {label}: greedy={c['greedy_rate']:.4f} "
              f"arm1={c['arm1_rate']:.4f} ({a1['n_rescue']}/{a1['n_records']}) "
              f"arm2={c['arm2_rate']:.4f} ({a2['n_rescue']}/{a2['n_records']})")
        print(f"    arm1 gross={a1['gross_escape']:.4f} net={a1['net_escape']:.4f} "
              f"EOS={a1['eos_rate']:.4f} kick={a1['mean_kickstart_events']:.2f} "
              f"supp={a1['mean_suppression_steps']:.1f}")
        print(f"    arm2 gross={a2['gross_escape']:.4f} net={a2['net_escape']:.4f} "
              f"EOS={a2['eos_rate']:.4f} kick={a2['mean_kickstart_events']:.2f} "
              f"supp={a2['mean_suppression_steps']:.1f}")
    print("=" * 70)

    # ==================================================================
    # Write outputs.
    # ==================================================================
    with open(OUTPUT_JSONL, "w", encoding="utf-8") as f:
        for r in all_results:
            f.write(json.dumps(r) + "\n")
        f.write(json.dumps({"record_type": "smoke", **smoke}) + "\n")
        f.write(json.dumps({
            "record_type": "meta",
            "model_name": MODEL_NAME,
            "model_revision": MODEL_REVISION,
            "device": device,
            "dtype": str(dtype),
            "torch_version": torch.__version__,
            "seed": SEED,
            "band_low": spectral_threshold,
            "sampling_temperature": SAMPLING_TEMPERATURE,
            "sampling_top_p": SAMPLING_TOP_P,
            "rescue_arm1_t2s": int(
                tables["escape"]["t2s_degenerate"]["arm1_agg"]["n_rescue"]
            ),
            "rescue_arm1_qwen": int(
                tables["escape"]["qwen_degenerate"]["arm1_agg"]["n_rescue"]
            ),
            "rescue_arm1_heldout_v2": int(
                tables["escape"]["heldout_degenerate_v2"]["arm1_agg"]["n_rescue"]
            ),
            "rescue_arm2_t2s": int(
                tables["escape"]["t2s_degenerate"]["arm2_agg"]["n_rescue"]
            ),
            "rescue_arm2_qwen": int(
                tables["escape"]["qwen_degenerate"]["arm2_agg"]["n_rescue"]
            ),
            "rescue_arm2_heldout_v2": int(
                tables["escape"]["heldout_degenerate_v2"]["arm2_agg"]["n_rescue"]
            ),
            "wall_clock_s": time.time() - t_start,
        }) + "\n")
    print(f"\nwrote {OUTPUT_JSONL} ({len(all_results)} record lines + "
          f"sidecar lines)")

    write_markdown_report(ctx)
    print(f"wrote {OUTPUT_MD}")

    print(f"\ntotal wall clock: {time.time() - t_start:.1f} s")
    print("night-014 measurement complete")


if __name__ == "__main__":
    main()
